In [45]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [46]:
dataset = pd.read_csv("CKD.csv")
dataset.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.46,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.11,57.48,3.08,137.53,4.63,12.52,38.87,8408.19,4.71,no,no,no,yes,yes,no,yes
1,3.0,76.46,c,2.0,0.0,normal,normal,notpresent,notpresent,148.11,22.00,0.70,137.53,4.63,10.70,34.00,12300.00,4.71,no,no,no,yes,poor,no,yes
2,4.0,76.46,a,1.0,0.0,normal,normal,notpresent,notpresent,99.00,23.00,0.60,138.00,4.40,12.00,34.00,8408.19,4.71,no,no,no,yes,poor,no,yes
3,5.0,76.46,d,1.0,0.0,normal,normal,notpresent,notpresent,148.11,16.00,0.70,138.00,3.20,8.10,38.87,8408.19,4.71,no,no,no,yes,poor,yes,yes
4,5.0,50.00,c,0.0,0.0,normal,normal,notpresent,notpresent,148.11,25.00,0.60,137.53,4.63,11.80,36.00,12400.00,4.71,no,no,no,yes,poor,no,yes

In [47]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset.shape
pd.set_option("display.max.columns",None)
pd.set_option("display.precision",2)
dataset.head()

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,sg_b,sg_c,sg_d,sg_e,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.0,76.46,3.0,0.0,148.11,57.48,3.08,137.53,4.63,12.52,38.87,8408.19,4.71,0,1,0,0,1,0,0,0,0,0,0,1,1,0,1
1,3.0,76.46,2.0,0.0,148.11,22.00,0.70,137.53,4.63,10.70,34.00,12300.00,4.71,0,1,0,0,1,1,0,0,0,0,0,1,0,0,1
2,4.0,76.46,1.0,0.0,99.00,23.00,0.60,138.00,4.40,12.00,34.00,8408.19,4.71,0,0,0,0,1,1,0,0,0,0,0,1,0,0,1
3,5.0,76.46,1.0,0.0,148.11,16.00,0.70,138.00,3.20,8.10,38.87,8408.19,4.71,0,0,1,0,1,1,0,0,0,0,0,1,0,1,1
4,5.0,50.00,0.0,0.0,148.11,25.00,0.60,137.53,4.63,11.80,36.00,12400.00,4.71,0,1,0,0,1,1,0,0,0,0,0,1,0,0,1

In [48]:
indep=dataset[["age","bp","al","su","bgr","bu","sc","sod","pot","hrmo","pcv","wc","rc","sg_b","sg_c","sg_d","sg_e","rbc_normal","pc_normal","pcc_present","ba_present","htn_yes","dm_yes","cad_yes","appet_yes","pe_yes","ane_yes"]]
dep=dataset[["classification_yes"]]
indep

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,sg_b,sg_c,sg_d,sg_e,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.00,76.46,3.0,0.0,148.11,57.48,3.08,137.53,4.63,12.52,38.87,8408.19,4.71,0,1,0,0,1,0,0,0,0,0,0,1,1,0
1,3.00,76.46,2.0,0.0,148.11,22.00,0.70,137.53,4.63,10.70,34.00,12300.00,4.71,0,1,0,0,1,1,0,0,0,0,0,1,0,0
2,4.00,76.46,1.0,0.0,99.00,23.00,0.60,138.00,4.40,12.00,34.00,8408.19,4.71,0,0,0,0,1,1,0,0,0,0,0,1,0,0
3,5.00,76.46,1.0,0.0,148.11,16.00,0.70,138.00,3.20,8.10,38.87,8408.19,4.71,0,0,1,0,1,1,0,0,0,0,0,1,0,1
4,5.00,50.00,0.0,0.0,148.11,25.00,0.60,137.53,4.63,11.80,36.00,12400.00,4.71,0,1,0,0,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.49,70.00,0.0,0.0,219.00,36.00,1.30,139.00,3.70,12.50,37.00,9800.00,4.40,0,0,0,0,1,1,0,0,0,0,0,1,0,0
395,51.49,70.00,0.0,2.0,220.00,68.00,2.80,137.53,4.63,8.70,27.00,8408.19,4.71,0,1,0,0,1,1,0,0,1,1,0,1,0,1
396,51.49,70.00,3.0,0.0,110.00,115.00,6.00,134.00,2.70,9.10,26.00,9200.00,3.40,0,1,0,0,1,1,0,0,1,1,0,0,0,0
397,51.49,90.00,0.0,0.0,207.00,80.00,6.80,142.00,5.50,8.50,38.87,8408.19,4.71,0,0,0,0,1,1,0,0,1,1,0,1,0,1
398,51.49,80.00,0.0,0.0,100.00,49.00,1.00,140.00,5.00,16.30,53.00,8500.00,4.90,0,0,0,0,1,1,0,0,0,0,0,1,0,0

In [49]:
from sklearn.model_selection import train_test_split
X_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [37]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
param_grid={"criterion":["gini",'entropy'],'splitter':['best','random'],
            "max_features":['auto','sqrt','log2']}
grid=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=3,cv=5,n_jobs=-1,scoring="f1_weighted")
grid.fit(X_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:   16.1s
[Parallel(n_jobs=-1)]: Done  60 out of  60 | elapsed:   16.5s finished

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_weighted', verbose=3)

In [50]:
re=grid.cv_results_
grid_predict=grid.predict(x_test)

In [51]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predict)

In [52]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predict)
print(clf_report)

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        45
           1       1.00      0.96      0.98        75

    accuracy                           0.97       120
   macro avg       0.97      0.98      0.97       120
weighted avg       0.98      0.97      0.98       120

In [41]:
print(cm)

[[45  0]
 [ 3 72]]

In [13]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003125,0.006251,0.000000,0.000000,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",0.855956,0.859649,0.821429,0.890909,0.908566,0.867002,0.030047,2
1,0.009374,0.012499,0.006251,0.007656,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",0.891967,0.807902,0.824958,0.852738,0.871992,0.849823,0.030678,3
2,0.003429,0.006858,0.000000,0.000000,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.763925,0.824561,0.823129,0.856749,0.907273,0.834501,0.046877,6
3,0.003126,0.006252,0.003125,0.006249,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.841261,0.807902,0.789152,0.835418,0.847453,0.824117,0.022134,9
4,0.003125,0.006250,0.003125,0.006250,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.715577,0.859649,0.840114,0.871992,0.850396,0.827020,0.057305,8
5,0.001200,0.002401,0.000976,0.001952,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.842829,0.783934,0.824293,0.837173,0.890909,0.835466,0.034366,5
6,0.003125,0.006250,0.006251,0.007656,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",0.800244,0.805986,0.769053,0.927935,0.909541,0.841726,0.063481,4
7,0.006250,0.007655,0.000000,0.000000,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",0.824561,0.859649,0.733523,0.800990,0.873357,0.818451,0.049475,11
8,0.006249,0.007653,0.000000,0.000000,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.836563,0.787055,0.787755,0.856749,0.850396,0.823405,0.030330,10
9,0.012521,0.018225,0.003125,0.006250,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.826042,0.842829,0.737667,0.854545,0.908566,0.833593,0.055314,7
10,0.003125,0.006250,0.006256,0.007661,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.858037,0.860834,0.823129,0.927935,0.908566,0.875280,0.037539,1
11,0.003133,0.006267,0.006248,0.007652,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.735435,0.805986,0.789152,0.871992,0.758911,0.791976,0.046527,12

In [53]:
Future_predict=grid.predict([[2,76,3,0,148.1,57.8,3.08,137.53,4.63,12.52,38.87,8403.3,4.71,0,0,0,0,1,0,0,0,0,0,0,1,1,0]])
Future_predict

array([0], dtype=uint8)